name: train_reservation_kata
version: 0.0.1
description: A simple console application.
#dependencies:
#  foo_bar: '>=1.0.0 <2.0.0'
dependencies:
  shelf: "^0.6.3"
  option: "^1.1.0"
  test: "^0.12.4+9"
  mockito: "^0.11.0"